[package]
name = "pancake-db-client"
version = "0.0.0-alpha.0"
authors = ["mwlon <m.w.loncaric@gmail.com>"]
edition = "2018"

[dependencies]
hyper = {version="0.14.9", features=["full"]}
pancake-db-core = {path="../core", version="0.0.0-alpha.0"}
pancake-db-idl = "0.0.0-alpha.0"
protobuf = "3.0.0-alpha.1"
tokio = {version="1.2.0", features=["macros"]}
